export const GET_BOOKS_IN_PROGRESS = "GET_BOOKS_IN_PROGRESS";
export const GET_BOOKS_COMPLETED = "GET_BOOKS_COMPLETED";

export const ADD_BOOK_IN_PROGRESS = "ADD_BOOK_IN_PROGRESS";
export const ADD_BOOK_COMPLETED = "ADD_BOOK_COMPLETED";
export const DELETE_BOOK_IN_PROGRESS = "DELETE_BOOK_IN_PROGRESS";
export const DELETE_BOOK_COMPLETED = "DELETE_BOOK_COMPLETED";
export const SET_TO_UPDATE_MODE = "SET_TO_UPDATE_MODE";
export const SET_TO_ADD_MODE = "SET_TO_ADD_MODE";
export const UPDATE_BOOK_IN_PROGRESS = "UPDATE_BOOK_IN_PROGRESS";
export const UPDATE_BOOK_COMPLETED = "UPDATE_BOOK_COMPLETED";
export const ERROR = "ERROR";
